### ISSUE TITLE
Upgrade spring boot services

### ISSUE THREAD

**Issue by jaserud** [imicroseq/roadmap#35]
Services to update:
- [x] singularity
- [x] muse

Overture services to import:
- [x] SONG
- [ ] Score
- [x] maestro
- [ ] EGO

**Comment by jaserud** [comment]
All prs for cancogen services:
https://github.com/cancogen-virus-seq/muse/pull/88
https://github.com/cancogen-virus-seq/singularity/pull/34

**Comment by ghost** [comment]
@caravinci/ @joneubank can you please take a look. 

I guess this is the reason we are facing different system behaviors in `prod `vs `dev`

**Comment by justincorrigible** [comment]
By the looks of it, as of today, only Score and Ego are missing the upgrades.
We have the others up to 2.6.6 both in dev and prod

**Comment by joneubank** [comment]
We are closing this ticket in favour of tracking the spring boot version upgrade in score and ego directly, instead of in the virus-seq roadmap.

The changes for Score will likely resemble the changes made in Song, where the new version of Spring Web Security will change the model for validating both ego JWT and API keys.

Changes in Ego could be more challenging as Ego both validates incoming tokens and generates new tokens on request.

Singularity, Muse, Song, and Maestro were all updated and those updated versions have been deployed in VirusSeq.

**Comment by ghost** [comment]
https://github.com/overture-stack/ego/issues/661
https://github.com/overture-stack/score/issues/340

**Comment by joneubank** [comment]
Tickets tracking remaining work:
Score - https://github.com/overture-stack/score/issues/340
Ego - https://github.com/overture-stack/ego/issues/661
